### ISSUE TITLE
Missing filters for series

### ISSUE THREAD

**Issue by djmulder** [OFark/Compressarr#2]
Hi,

I know it's probably not a bug, but there's quite a difference between filters for series as there is for movies. I can imagine it's because sonarr doesn't give all the info needed? 

I mainly have the issue that I've got quite a few files with a bad codec/Format: my movie filter is filtering format:VC-1 or codec:Unknown 

But yeh I can't seem to add this filter for episodes in series. 

Is there a way to still do this? 

Perhaps it's an idea to use the mediainfo tool to get all this data? 

Also I notice I can't filter for something like "Dolby Vision" which would be ideal (as I can't seem to get this to properly play on plex due to it not doing HDR tone mapping properly)

**Comment by OFark** [comment]
Yes, Sonarr offers a lot less information than Radarr, but Video Codec is something is does do:
![image](https://user-images.githubusercontent.com/4558132/136752259-a359fbf3-c31f-4f30-b722-11124e3c3003.png)

One of the reasons I use Radarr/Sonarr is that you don't have to wait for the system to scan all of your files before you can use it, that information is already somewhere.

Dolby Vision isn't something I've seen as a piece of information anywhere, either from FFmpeg or from Radarr/Sonarr, not sure how I would get that.

**Comment by djmulder** [comment]
Interesting thanks that should get me somewhere. Although I really need to find all the VC-1s as that plays horrid over plex

and yeh.. is there no way to just integrate [mediainfo](https://hub.docker.com/r/jlesage/mediainfo)? and have a process just go over all the files (sure... pain on the system, but if done once you shouldn't have to do it again) Then you have more metadata to play with :D

**Comment by OFark** [comment]
It seems like it would be a single pass, right? But when you get into it; what happens if there are more files added, got to go looking for them on a schedule to make sure all the data is available. What happens if Sonarr decides to get a better version of the file, same file name, different content. Need to register an event on file change, but what if the app isn't running when that happens? There are problems that can be overcome, but the simplest solution to get this off the ground was to just use the Radarr/Sonarr API.
