### ISSUE TITLE
Radarr URL Not Found

### ISSUE THREAD

**Issue by Getn67** [OFark/Compressarr#4]
I have checked that all three services are on the same network, and continue to not have the ability to add Radarr into the options. radarr:80 shows a connection refused error meaning using the name is correct. I have also tried the IP address to the same result.

https://pastebin.com/s5YgZmja <-Logs

![image](https://user-images.githubusercontent.com/51862012/147376693-3343efbe-f749-48f1-815d-345d015e745a.png)

**Comment by OFark** [comment]
Thank you for reporting this, and thank you for the logs.

I can see the issue is a Socket Exception 111. Which means Connection Refused. This doesn't mean that it was actively refused as in a firewall said "no", it just wasn't responded to, which could be any IP/port that has no binding. 

I see you got Sonarr connected, the connection code is the same for both services. Literally the same lines of code, so the issue isn't with Compressarr or the Docker it's contained within. Could be Radarr settings, is it on a VPN? What version of Radarr are you using?

**Comment by Getn67** [comment]
Radarr
![image](https://user-images.githubusercontent.com/51862012/147487931-8c6f916e-5d30-4dbd-8f23-92ab2162ffb6.png)
Sonarr
![image](https://user-images.githubusercontent.com/51862012/147487979-ef5182b0-2f21-4296-97d3-0232426c23af.png)

All three services are on the same docker network, assigned static IPs, and have default port configs. All have the same guid/puid configs as well.

**Comment by OFark** [comment]
Yeah, I've had reports of issues before with version 4 of Radarr. Where did you get it from? The latest official release of Radarr is: https://github.com/Radarr/Radarr/releases/tag/v3.2.2.5080

**Comment by Getn67** [comment]
Well, I'll give you that. I am using the nightly branch in docker via linuxserver.io. I have removed the nightly version, and have installed the default branch (currently 3.2.2.5080) and it has linked successfully.

**Comment by OFark** [comment]
Maybe they have overhauled the API for version 4. When I get time I'll take a look. Thanks for letting me know.
